import type { ComboboxItem, ComboboxParsedItem, OptionsFilter } from '@mantine/core';
import { Text } from '@mantine/core';
import { useEffect, useMemo, useState } from 'react';
import { globalTranslationHandle } from 'shared';
import MultiSelect from '@/elements/input/MultiSelect.tsx';
import { MAX_TARGETS, PACKAGE_NAME } from '../lib/schemas.ts';
import { allTranslationKeys, currentText, englishText } from '../lib/targets.ts';
import { useExtTranslations } from '../translations.ts';

/** `[name, width, height, svg path]`, generated by scripts/generate-icons.mjs */
type IconEntry = [string, number, number, string];

interface TargetOption {
  /** current-language text, or the icon name */
  label: string;
  english?: string;
  key?: string;
  icon?: IconEntry;
}

// the icon list is a static file (frontend/public) so it is only downloaded on this page,
// importing the icon packages here would pull all of them into the panel's shared bundle
let iconsPromise: Promise<IconEntry[]> | null = null;

function loadIcons(): Promise<IconEntry[]> {
  iconsPromise ??= fetch(`/${PACKAGE_NAME}/icons.json`)
    .then((response) => {
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return response.json() as Promise<IconEntry[]>;
    })
    .catch((err) => {
      console.warn('[menu music] failed to load icon list', err);
      iconsPromise = null;
      return [];
    });

  return iconsPromise;
}

function IconPreview({ icon: [, width, height, path] }: { icon: IconEntry }) {
  return (
    <svg viewBox={`0 0 ${width} ${height}`} className='h-4 w-5 shrink-0' aria-hidden='true'>
      <path fill='currentColor' d={path} />
    </svg>
  );
}

/** Translation keys first, built once per language. */
function buildKeyOptions(): Map<string, TargetOption> {
  const options = new Map<string, TargetOption>();
  for (const key of allTranslationKeys()) {
    const label = currentText(key) ?? key;
    options.set(`key:${key}`, { label, english: englishText(key), key });
  }
  return options;
}

interface Props {
  label: string;
  description: string;
  value: string[];
  error?: string;
  onChange: (value: string[]) => void;
}

/**
 * Searchable picker for what a sound reacts to: the panel's own texts (stored as translation keys, so
 * they match in every language) and icons for icon-only buttons. Search order: the text in the language
 * the admin uses, then English, then the key itself; icons by name.
 */
export default function TargetPicker({ label, description, value, error, onChange }: Props) {
  // subscribes to the panel translations, so this re-renders when the language data changes
  const { t: tExt } = useExtTranslations();
  const [icons, setIcons] = useState<IconEntry[]>([]);

  useEffect(() => {
    loadIcons().then(setIcons);
  }, []);

  // rebuilt whenever the panel's translations change (language switch or language file loaded)
  const keyOptions = useMemo(buildKeyOptions, [globalTranslationHandle]);

  const options = useMemo(() => {
    const all = new Map(keyOptions);
    for (const icon of icons) all.set(`icon:${icon[0]}`, { label: icon[0], icon });
    // keep targets that no longer exist (e.g. a key removed in a newer panel) visible and removable
    for (const target of value) {
      if (!all.has(target)) all.set(target, { label: target });
    }
    return all;
  }, [keyOptions, icons, value]);

  const data = useMemo<ComboboxItem[]>(
    () =>
      Array.from(options, ([target, option]) => ({
        value: target,
        label: option.icon ? tExt('config.sounds.iconLabel', { name: option.label }) : option.label,
      })),
    [options, tExt],
  );

  const filter: OptionsFilter = ({ options: items, search, limit }) => {
    const query = search.trim().toLowerCase();
    if (!query) return items.slice(0, limit);

    const ranked: { item: ComboboxParsedItem; rank: number; length: number }[] = [];
    for (const item of items) {
      if (!('value' in item)) continue;
      const option = options.get(item.value);
      if (!option) continue;

      const text = option.label.toLowerCase();
      let rank = -1;
      if (option.icon) {
        if (text.startsWith(query)) rank = 1;
        else if (text.includes(query)) rank = 4;
      } else if (text.startsWith(query)) rank = 0;
      else if (text.includes(query)) rank = 2;
      else if (option.english?.toLowerCase().includes(query)) rank = 3;
      else if (option.key?.toLowerCase().includes(query)) rank = 5;

      if (rank >= 0) ranked.push({ item, rank, length: text.length });
    }

    ranked.sort((a, b) => a.rank - b.rank || a.length - b.length);
    return ranked.slice(0, limit).map(({ item }) => item);
  };

  return (
    <MultiSelect
      label={label}
      description={description}
      placeholder={tExt('config.sounds.targetsPlaceholder', {})}
      data={data}
      value={value}
      onChange={(next) => onChange(next.slice(0, MAX_TARGETS))}
      error={error}
      filter={filter}
      searchable
      clearable
      hidePickedOptions
      limit={40}
      maxDropdownHeight={300}
      renderOption={({ option }) => {
        const target = options.get(option.value);
        if (!target) return option.label;

        if (target.icon) {
          return (
            <span className='flex items-center gap-2'>
              <IconPreview icon={target.icon} />
              <span>{option.label}</span>
            </span>
          );
        }

        return (
          <div className='min-w-0'>
            <Text size='sm' truncate>
              {target.label}
            </Text>
            <Text size='xs' c='dimmed' ff='monospace' truncate>
              {target.english && target.english !== target.label ? `${target.english} · ${target.key}` : target.key}
            </Text>
          </div>
        );
      }}
    />
  );
}
